services:
  - type: web
    name: clausespy
    env: python
    buildCommand: "./render_build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: clausespy-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
